apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tour-of-heroes-web
    role: frontend
  name: tour-of-heroes-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tour-of-heroes-web
      role: frontend
  template:
    metadata:
      labels:
        app: tour-of-heroes-web
        role: frontend
    spec:
      containers:
        - image: ghcr.io/0gis0/tour-of-heroes-flask/tour-of-heroes-flask:49c7562
          name: tour-of-heroes-web
          ports:
            - containerPort: 5002
              name: web
          env:
            - name: API_URL
              value: http://tour-of-heroes-api.tour-of-heroes/api/hero
