apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
spec:
  storageClassName: managed-csi
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce